module Seerstack
  module Resources
    class Users
      def identify: (
        user_id: String,
        ?attributes: ::Hash[Symbol, top?],
        ?email: String,
        ?name: String,
        ?request_options: Seerstack::request_opts
      ) -> Seerstack::Models::UserIdentifyResponse

      def initialize: (client: Seerstack::Client) -> void
    end
  end
end
